/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmloginejemplo;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class frmMenuAdministradores extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuAdministradores
     */
    public frmMenuAdministradores() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rSButtonRegistrar = new rsbuttom.RSButtonMetro();
        rSButtonProductos = new rsbuttom.RSButtonMetro();
        rSButtonPedidos = new rsbuttom.RSButtonMetro();
        rSButtonVentas = new rsbuttom.RSButtonMetro();
        rSButtonFacturas = new rsbuttom.RSButtonMetro();
        rSButtonCerrarSesion = new rsbuttom.RSButtonMetro();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido Administrador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        rSButtonRegistrar.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        rSButtonRegistrar.setText("Registrar Usuario Nuevo");
        rSButtonRegistrar.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonRegistrar.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonRegistrar.setColorPressed(new java.awt.Color(153, 153, 153));
        rSButtonRegistrar.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButtonRegistrar.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonRegistrar.setColorTextPressed(new java.awt.Color(0, 0, 0));
        rSButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRegistrarActionPerformed(evt);
            }
        });

        rSButtonProductos.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/market.png"))); // NOI18N
        rSButtonProductos.setText("          Productos             ");
        rSButtonProductos.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonProductos.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonProductos.setColorPressed(new java.awt.Color(153, 153, 153));
        rSButtonProductos.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButtonProductos.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonProductos.setColorTextPressed(new java.awt.Color(0, 0, 0));
        rSButtonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonProductosActionPerformed(evt);
            }
        });

        rSButtonPedidos.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chat.png"))); // NOI18N
        rSButtonPedidos.setText("         Pedidos                  ");
        rSButtonPedidos.setToolTipText("");
        rSButtonPedidos.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonPedidos.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonPedidos.setColorPressed(new java.awt.Color(153, 153, 153));
        rSButtonPedidos.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButtonPedidos.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonPedidos.setColorTextPressed(new java.awt.Color(0, 0, 0));
        rSButtonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonPedidosActionPerformed(evt);
            }
        });

        rSButtonVentas.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/collection.png"))); // NOI18N
        rSButtonVentas.setText("         Ventas                 ");
        rSButtonVentas.setToolTipText("");
        rSButtonVentas.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonVentas.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonVentas.setColorPressed(new java.awt.Color(153, 153, 153));
        rSButtonVentas.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButtonVentas.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonVentas.setColorTextPressed(new java.awt.Color(0, 0, 0));
        rSButtonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonVentasActionPerformed(evt);
            }
        });

        rSButtonFacturas.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/feeedback.png"))); // NOI18N
        rSButtonFacturas.setText("          Facturas               ");
        rSButtonFacturas.setToolTipText("");
        rSButtonFacturas.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonFacturas.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonFacturas.setColorPressed(new java.awt.Color(153, 153, 153));
        rSButtonFacturas.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButtonFacturas.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonFacturas.setColorTextPressed(new java.awt.Color(0, 0, 0));
        rSButtonFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonFacturasActionPerformed(evt);
            }
        });

        rSButtonCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        rSButtonCerrarSesion.setText("Cerrar Sesión");
        rSButtonCerrarSesion.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonCerrarSesion.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonCerrarSesion.setColorPressed(new java.awt.Color(153, 153, 153));
        rSButtonCerrarSesion.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButtonCerrarSesion.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonCerrarSesion.setColorTextPressed(new java.awt.Color(0, 0, 0));
        rSButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addComponent(rSButtonProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonFacturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(rSButtonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(rSButtonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(rSButtonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(rSButtonFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(rSButtonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRegistrarActionPerformed
        // TODO add your handling code here:
           frmUsuarios fra = new frmUsuarios();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonRegistrarActionPerformed

    private void rSButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonProductosActionPerformed
        // TODO add your handling code here:
         frmProductos fra = new frmProductos();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonProductosActionPerformed

    private void rSButtonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonPedidosActionPerformed
        // TODO add your handling code here:
           FrmPedidos fra = new FrmPedidos();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonPedidosActionPerformed

    private void rSButtonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonVentasActionPerformed
        // TODO add your handling code here:
             frmVentas fra = new frmVentas();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonVentasActionPerformed

    private void rSButtonFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonFacturasActionPerformed
        // TODO add your handling code here:
             frmFactura fra = new frmFactura();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonFacturasActionPerformed

    private void rSButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
           int Resp= JOptionPane.showConfirmDialog(null,"¿Esta seguro de cerrar sesión?", "Cuidado",JOptionPane.YES_NO_OPTION);
if(Resp==0){
      frmLogin log = new frmLogin();
        log.show();
        this.hide();
}
    }//GEN-LAST:event_rSButtonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuAdministradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private rsbuttom.RSButtonMetro rSButtonCerrarSesion;
    private rsbuttom.RSButtonMetro rSButtonFacturas;
    private rsbuttom.RSButtonMetro rSButtonPedidos;
    private rsbuttom.RSButtonMetro rSButtonProductos;
    private rsbuttom.RSButtonMetro rSButtonRegistrar;
    private rsbuttom.RSButtonMetro rSButtonVentas;
    // End of variables declaration//GEN-END:variables
}
